# Generated by Django 2.0.6 on 2018-06-26 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserRights',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': (('change_clock', 'Can change clock status'), ('change_status', 'Can change game status'), ('change_config', 'Can change game config'), ('play_videos', 'Can play videos')),
                'managed': False,
            },
        ),
    ]
